[PATHS]
logging = data
logfile = log.txt
data = data
db_file = power.db

[CONNECTION]
sma_host = SMA1992015033
sma_pwd = Lieke_11

[WEBSERVER]
port = 8080

[RS232]
port = /dev/ttyUSB0
# port = COM3
baudrate = 119200
parity = serial.PARITY_ODD
stopbits = serial.STOPBITS_TWO
bytesize = serial.SEVENBITS

[ZWAVE]
configpath_windows = C:/Users/erikk/PycharmProjects/Zwave station/venv/Lib/site-packages/python_openzwave/ozw_config
device_windows = COM3
configpath_linux = /usr/etc/openzwave/config/
device_linux = /dev/ttyACM0
nodes = 2:badkamer
    3:woonkamer
subscriptions = 2:Temperature,Relative Humidity
    3:Temperature,Relative Humidity

[DATARETRIEVAL]
p1_signals = TIMESTAMP
    USAGE_TARIFF_1
    USAGE_TARIFF_2
    PRODUCTION_TARIFF_1
    PRODUCTION_TARIFF_2
    TARIFF
    CURRENT_USAGE
    CURRENT_PRODUCTION
    CURRENT_USAGE_PHASE1
    CURRENT_USAGE_PHASE2
    CURRENT_USAGE_PHASE3
    CURRENT_PRODUCTION_PHASE1
    CURRENT_PRODUCTION_PHASE2
    CURRENT_PRODUCTION_PHASE3
    CUMULATIVE_GAS

[DATASTORAGE]
p1_data_store = P1

data_stores = P1
    Solar
    zwave_badkamer
    zwave_huiskamer
    P1_Solar
    gas_hourly
    gas_daily
    gas_monthly
    verbruik_daily
    zwave_daily
    meterstand

P1_name = P1
P1_persistency = volatile
P1_lifespan = circular
P1_buflen = 2*60*6
P1_signals = CURRENT_USAGE
    CURRENT_PRODUCTION
    CURRENT_USAGE_PHASE1
    CURRENT_USAGE_PHASE2
    CURRENT_USAGE_PHASE3
    CURRENT_PRODUCTION_PHASE1
    CURRENT_PRODUCTION_PHASE2
    CURRENT_PRODUCTION_PHASE3
    CUMULATIVE_GAS

Solar_name = Solar
Solar_persistency = volatile
Solar_lifespan = circular
SolarP1_buflen = 2*60*6
Solar_signals = SOLAR

zwave_badkamer_db = power.db
zwave_badkamer_name = zwave_woonkamer
zwave_badkamer_persistency = persistent
zwave_badkamer_lifespan = circular
zwave_badkamer_buflen = 30*24*60
zwave_badkamer_signals = TEMPERATURE
    RELATIVE_HUMIDITY

zwave_huiskamer_db = power.db
zwave_huiskamer_name = zwave_badkamer
zwave_huiskamer_persistency = persistent
zwave_huiskamer_lifespan = circular
zwave_huiskamer_buflen = 30*24*60
zwave_huiskamer_signals = TEMPERATURE
    RELATIVE_HUMIDITY

P1_Solar_name = P1_Solar
P1_Solar_db = power.db
P1_Solar_persistency = persistent
P1_Solar_lifespan = circular
P1_Solar_buflen = 30*24*60*6
P1_Solar_signals = CURRENT_USAGE
    CURRENT_PRODUCTION
    CURRENT_USAGE_PHASE1
    CURRENT_USAGE_PHASE2
    CURRENT_USAGE_PHASE3
    CURRENT_PRODUCTION_PHASE1
    CURRENT_PRODUCTION_PHASE2
    CURRENT_PRODUCTION_PHASE3
    SOLAR

gas_hourly_name = gas_hourly
gas_hourly_db = power.db
gas_hourly_persistency = persistent
gas_hourly_lifespan = circular
gas_hourly_sampling_time_minutes = 60
gas_hourly_buflen = 30*24
gas_hourly_signals = USAGE_GAS

gas_daily_name = gas_daily
gas_daily_db = power.db
gas_daily_persistency = persistent
gas_daily_lifespan = circular
gas_daily_sampling_time_minutes = 24*60
gas_daily_buflen = 30*24
gas_daily_signals = USAGE_GAS

gas_monthly_name = gas_monthly
gas_monthly_db = power.db
gas_monthly_persistency = persistent
gas_monthly_lifespan = circular
gas_monthly_sampling_time_minutes = 30*24*60
gas_monthly_buflen = 30*24
gas_monthly_signals = USAGE_GAS

verbruik_daily_name = verbruik_daily
verbruik_daily_db = power.db
verbruik_daily_persistency = persistent
verbruik_daily_lifespan = linear
verbruik_daily_sampling_time_minutes = 24*60
verbruik_daily_signals = USAGE_GAS

zwave_daily_name = zwave_daily
zwave_daily_db = power.db
zwave_daily_persistency = persistent
zwave_daily_lifespan = linear
zwave_daily_sampling_time_minutes = 24*60
zwave_daily_signals = USAGE_GAS

meterstand_name = meterstand
meterstand_db = power.db
meterstand_persistency = persistent
meterstand_lifespan = linear
meterstand_sampling_time_minutes = 30*24*60
meterstand_signals = USAGE_GAS

min_storage_time_diff_seconds = 1

[SCHEDULER]
scheduled_jobs = merge_P1_solar assess_gas_usage get_gas_daily get_gas_monthly get_verbruik_daily get_zwave_daily

merge_P1_solar_sources = P1 Solar
merge_P1_solar_destination = P1_Solar
merge_P1_solar_interval_minutes = 1
merge_P1_solar_start_delay_minutes = 0
merge_P1_solar_operation = SHIFT SOLAR

assess_gas_usage_sources = P1
assess_gas_usage_destination = gas_hourly
assess_gas_usage_interval_minutes = 60
assess_gas_usage_start_delay_minutes = 0
assess_gas_usage_operation = DIFF CUMULATIVE_GAS

get_gas_daily_sources = gas_hourly
get_gas_daily_destination = gas_daily
get_gas_daily_interval_minutes = 24*60
get_gas_daily_start_delay_minutes = 0
get_gas_daily_operation = AVG USAGE_GAS

[PROCESSING]
shift_in_seconds = -17.8
signal_to_shift = SOLAR

differential_source_signal = CUMULATIVE_GAS
filtered_data_store = gas_cum_temp
differential_dest_data_store = gas_hourly
differential_dest_signal = USAGE_GAS
differential_dest_unit = m3/h
