[PATHS]
logging = data
logfile = log.txt
data = data
db_file = power.db

[CONNECTION]
sma_host = SMA1992015033
sma_pwd = Lieke_11

[WEBSERVER]
port = 8080

[RS232]
port_linux = /dev/ttyUSB0
port_windows = COM4
baudrate = 119200
parity = serial.PARITY_ODD
stopbits = serial.STOPBITS_TWO
bytesize = serial.SEVENBITS

[ZWAVE]
configpath_windows = C:\Users\erikk\PycharmProjects\PowerLogger\.venv\Lib\site-packages\python_openzwave\ozw_config
logfile = OZW_Log.log
device_windows = COM3
configpath_linux = /home/erik/Python-projects/venv_3_8_20/lib/python3.8/site-packages/python_openzwave/ozw_config
device_linux = /dev/ttyACM0
nodes = 2:badkamer
    3:woonkamer
subscriptions = 2:Temperature,Relative Humidity
    3:Temperature,Relative Humidity

[DATARETRIEVAL]
p1_signals = TIMESTAMP
    USAGE_TARIFF_1
    USAGE_TARIFF_2
    PRODUCTION_TARIFF_1
    PRODUCTION_TARIFF_2
    TARIFF
    CURRENT_USAGE
    CURRENT_PRODUCTION
    CURRENT_USAGE_PHASE1
    CURRENT_USAGE_PHASE2
    CURRENT_USAGE_PHASE3
    CURRENT_PRODUCTION_PHASE1
    CURRENT_PRODUCTION_PHASE2
    CURRENT_PRODUCTION_PHASE3
    CUMULATIVE_GAS

[DATASTORAGE]
p1_data_store = P1
sma_data_store = Solar
zwave_data_store = zwave

data_stores = P1
    Solar
    zwave
    P1_Solar
    gas_hourly
    gas_daily
    gas_monthly
    verbruik_daily
    zwave_daily
    meterstand

P1_name = P1
P1_persistency = volatile
P1_lifespan = circular
P1_buflen = 2*60*6
P1_signals = CURRENT_USAGE
    CURRENT_PRODUCTION
    CURRENT_USAGE_PHASE1
    CURRENT_USAGE_PHASE2
    CURRENT_USAGE_PHASE3
    CURRENT_PRODUCTION_PHASE1
    CURRENT_PRODUCTION_PHASE2
    CURRENT_PRODUCTION_PHASE3
    USAGE_TARIFF_1
    USAGE_TARIFF_2
    PRODUCTION_TARIFF_1
    PRODUCTION_TARIFF_2
    CUMULATIVE_GAS

Solar_name = Solar
Solar_persistency = volatile
Solar_lifespan = circular
Solar_buflen = 2*60*6
Solar_signals = SOLAR

zwave_db = power.db
zwave_name = zwave
zwave_persistency = persistent
zwave_lifespan = circular
zwave_buflen = 30*24*60
zwave_signals = TEMPERATURE_2
    RELATIVE_HUMIDITY_2
    TEMPERATURE_3
    RELATIVE_HUMIDITY_3

P1_Solar_name = P1_Solar
P1_Solar_db = power.db
P1_Solar_persistency = persistent
P1_Solar_lifespan = circular
P1_Solar_buflen = 30*24*60*6
P1_Solar_signals = CURRENT_USAGE
    CURRENT_PRODUCTION
    CURRENT_USAGE_PHASE1
    CURRENT_USAGE_PHASE2
    CURRENT_USAGE_PHASE3
    CURRENT_PRODUCTION_PHASE1
    CURRENT_PRODUCTION_PHASE2
    CURRENT_PRODUCTION_PHASE3
    SOLAR

gas_hourly_name = gas_hourly
gas_hourly_db = power.db
gas_hourly_persistency = persistent
gas_hourly_lifespan = circular
gas_hourly_sampling_period = HOUR
gas_hourly_buflen = 30*24
gas_hourly_signals = USAGE_GAS

gas_daily_name = gas_daily
gas_daily_db = power.db
gas_daily_persistency = persistent
gas_daily_lifespan = circular
gas_daily_sampling_period = DAY
gas_daily_buflen = 5*365
gas_daily_signals = USAGE_GAS

gas_monthly_name = gas_monthly
gas_monthly_db = power.db
gas_monthly_persistency = persistent
gas_monthly_lifespan = circular
gas_monthly_sampling_period = MONTH
gas_monthly_buflen = 30*24
gas_monthly_signals = USAGE_GAS

verbruik_daily_name = verbruik_daily
verbruik_daily_db = power.db
verbruik_daily_persistency = persistent
verbruik_daily_lifespan = linear
verbruik_daily_sampling_period = DAY
verbruik_daily_signals = CURRENT_USAGE
    CURRENT_PRODUCTION
    CURRENT_USAGE_PHASE1
    CURRENT_USAGE_PHASE2
    CURRENT_USAGE_PHASE3
    CURRENT_PRODUCTION_PHASE1
    CURRENT_PRODUCTION_PHASE2
    CURRENT_PRODUCTION_PHASE3
    SOLAR

zwave_daily_name = zwave_daily
zwave_daily_db = power.db
zwave_daily_persistency = persistent
zwave_daily_lifespan = linear
zwave_daily_sampling_period = DAY
zwave_daily_signals = TEMPERATURE_2
    RELATIVE_HUMIDITY_2
    TEMPERATURE_3
    RELATIVE_HUMIDITY_3

meterstand_name = meterstand
meterstand_db = power.db
meterstand_persistency = persistent
meterstand_lifespan = linear
meterstand_sampling_period = MONTH
meterstand_signals = USAGE_TARIFF_1
    USAGE_TARIFF_2
    PRODUCTION_TARIFF_1
    PRODUCTION_TARIFF_2
    CUMULATIVE_GAS

min_storage_time_diff_seconds = 1

[SCHEDULER]
scheduled_jobs = merge_P1_solar assess_gas_usage get_gas_daily get_gas_monthly get_verbruik_daily meterstanden

merge_P1_solar_sources = P1 Solar
merge_P1_solar_destination = P1_Solar
merge_P1_solar_interval_minutes = 1
merge_P1_solar_operation = SHIFT SOLAR

assess_gas_usage_sources = P1
assess_gas_usage_destination = gas_hourly
assess_gas_usage_interval_minutes = 60
assess_gas_usage_start_at_time = :30
assess_gas_usage_operation = DIFF CUMULATIVE_GAS

get_gas_daily_sources = gas_hourly
get_gas_daily_destination = gas_daily
get_gas_daily_periodicity = day
get_gas_daily_operation = INTEGRATE USAGE_GAS

get_gas_monthly_sources = gas_hourly
get_gas_monthly_destination = gas_monthly
get_gas_monthly_periodicity = month
get_gas_monthly_operation = INTEGRATE USAGE_GAS

get_verbruik_daily_sources = P1_Solar
get_verbruik_daily_destination = verbruik_daily
get_verbruik_daily_periodicity = day
get_verbruik_daily_operation = INTEGRATE *

get_zwave_daily_sources = zwave
get_zwave_daily_destination = zwave_daily
get_zwave_daily_periodicity = day
get_zwave_daily_operation = AVG *

meterstanden_sources = P1
meterstanden_destination = meterstand
meterstanden_periodicity = day
meterstanden_operation = VALUE *

[PROCESSING]
shift_in_seconds = -8.7
# was -17.6, -8.9 toegevoegd
# toch maar gewijzigd door -8.9 ervan af te trekken
