c_SECONDS_PER_MINUTE = 60
c_MINUTES_PER_HOUR = 60
c_HOURS_PER_DAY = 24
c_DAYS_PER_MONTH = 30
c_DAYS_PER_YEAR = 365

c_SECONDS_PER_HOUR = c_SECONDS_PER_MINUTE * c_MINUTES_PER_HOUR
c_SECONDS_PER_DAY = c_SECONDS_PER_MINUTE * c_MINUTES_PER_HOUR * c_HOURS_PER_DAY
c_MINUTES_PER_DAY = c_MINUTES_PER_HOUR * c_HOURS_PER_DAY
c_MINUTES_PER_MONTH = c_MINUTES_PER_HOUR * c_HOURS_PER_DAY * c_DAYS_PER_MONTH
c_MINUTES_PER_YEAR = c_MINUTES_PER_HOUR * c_HOURS_PER_DAY * c_DAYS_PER_YEAR
